### ISSUE TITLE
Checklist - opening to public

### ISSUE THREAD

**Issue by funkchaser** [gramaziokohler/compas_timber#102]
# Check-list 
TODOs for making `compas_timber` public by 16th May 2023:

- [ ] documentation / API: 
  - [x] consistent highlighting (e.g. COMPAS TIMBER/compas_timber, Beam/beam/`Beam` etc..) 
  - [ ] complete and check docstrings
  - [x] complete and check grasshopper tutorial
    - [x] add examples to download
  - [ ] update quick installation guide & create downloads
  - [ ] clean up README on the main repo page
  - [ ] add link to API to README
- [ ] [sort out github actions for proper release](https://github.com/gramaziokohler/compas_timber/issues/92)
- [x] close stale issues
- [x] delete stale branches
- [x]  delete branch `main` rename `dev` to `main`
- [ ] check permissions after public
- [ ] register a DOI (for citations)
- [ ] GKR website
- [ ] link with compas extensions?
